### PR TITLE
.Net Core compatibility

### PR DESCRIPTION
**Pull request by CBaptiste**

### CODE REVIEW

**Comment by CBaptiste** [comment]
@ChrisMcKee back on this pr (I forked yours)
After a few testing, I think we are loosing the .Net 4.0  compatibility no ? or I am mistaken ?
I am testing the compatibility of the PR with a few different platform

**Comment by ChrisMcKee** [comment]
@CBaptiste I set the base level at 4.5
https://github.com/ChrisMcKee/algoliasearch-client-csharp/blob/63a1090d99cf51eb6856e26218750d8c7698bcbc/Algolia.Search/Algolia.Search.csproj#L20

Technically anything prior to 4.6.2 is out of support anyway https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/ but I habitually keep lower targets.

**Comment by ChrisMcKee** [comment]
The HMAC should be right; in that the the hash generated matches the one generated by the API in python; where I had issues, the test hashes in the C# tests didn't seem to match up with the ones in the other platforms.

**Comment by CBaptiste** [comment]
alright, good to know :) thanks for the input. almost there ...

**Comment by CBaptiste** [comment]
Oh yes ! You had changed the hash, I just did not see it...why did you change it ? because if you just run the tests before this PR, the hashes match and the tests runs fine

**Comment by ChrisMcKee** [comment]
I changed it to match the identical input => output of the python driver (needed a sane source to work against) as the outputs in .net don't match. All the integration tests passed at the time so I did my happy dance and pushed.

**Comment by CBaptiste** [comment]
ok so @ChrisMcKee I quickly tested the secured api key we are generating with this PR, the engine says it is invalid, I m looking into it

**Comment by ChrisMcKee** [comment]
image

You'd see why I'd be confused by this 😛 
Granted this is on my branch; I've not pulled any changes in.

**Comment by CBaptiste** [comment]
maybe there is a misunderstood somewhere :)
your PR: https://github.com/algolia/algoliasearch-client-csharp/pull/331/files#diff-3d44626428ff506b9c026a18d6f1ea00L895 
the test on the API keys changed, and those new API keys are invalid

**Comment by ChrisMcKee** [comment]
@CBaptiste Yeah it didn't click; its was March, lots of codes gone by since then :wink: 
The hashes I generated for the left side came from the standard python hashlib 
```
import hashlib
import hmac
import base64
from pprint import pprint

securedKey = hmac.new("182634d8894831d5dbce3b3185c50881".encode('utf-8'), "tagFilters=%28public%2Cuser1%29&userToken=42".encode('utf-8'), hashlib.sha256).hexdigest()
pprint (base64.b64encode(("%s%s" % (securedKey, "tagFilters=%28public%2Cuser1%29&userToken=42")).encode('utf-8')).decode('utf-8'))
```
One I just generated for my own came back 

```
ZTBlZWNmZWEyNmIxMWFiNWRhODBhMzdhNTBiOGM4YzRmNTYwMzU5NjdkZGQ5ZmFlNTk0Nzc5NzU3ZWM2NGIwMHJlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==   C#

ZTBlZWNmZWEyNmIxMWFiNWRhODBhMzdhNTBiOGM4YzRmNTYwMzU5NjdkZGQ5ZmFlNTk0Nzc5NzU3ZWM2NGIwMHJlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==   Python
```
But yep I can replicate the issue by changing test initialise on AlgoliaClientTests to 

```
        [SetUp]
        public void TestInitialize()
        {
            _testApiKey = Environment.GetEnvironmentVariable("ALGOLIA_API_KEY") ?? "mykey";
            _testApplicationID = Environment.GetEnvironmentVariable("ALGOLIA_APPLICATION_ID") ?? "TJ8JVLYYX7";

            _client = new AlgoliaClient(_testApplicationID, _testApiKey);

            string secureAPI = _client.GenerateSecuredApiKey(_testApiKey, new Query().SetRestrictIndices(new[] { "algolia-csharp" }));

            _client = new AlgoliaClient(_testApplicationID, secureAPI);


            _index = _client.InitIndex(safe_name("algolia-csharp"));
        }
```

**Comment by CBaptiste** [comment]
interesting, 
When building the query string,  Uri.EscapeDataString in GetQueryString does not generate the same string in both project with the exact same parameter
in the old PCL: tagFilters=(public%2Cuser1)
in the new: tagFilters=%28public%2Cuser1%29

I don't know if it is linked to it at least that s a first behavior difference

**Comment by CBaptiste** [comment]
ok, prior to 4.5, values are not encoded

**Comment by ChrisMcKee** [comment]
Just to be extra clear*
I first went through the other projects 
image
To get that hash string; The algolia python lib does not directly manufacture the hmac and uses a library so I worked towards getting a match between the two. 
And prior to 4.5 vals wouldnt have been encoded

**Comment by ChrisMcKee** [comment]
Lol jinx  👍

**Comment by ChrisMcKee** [comment]
@CBaptiste the HMAC itself is fine 
image
After that its only converting to base64 

```
e0eecfea26b11ab5da80a37a50b8c8c4f56035967ddd9fae594779757ec64b00
```

becomes

```
ZTBlZWNmZWEyNmIxMWFiNWRhODBhMzdhNTBiOGM4YzRmNTYwMzU5NjdkZGQ5ZmFlNTk0Nzc5NzU3ZWM2NGIwMA==
```
in online "to base 64"

in .net its 

```
ZTBlZWNmZWEyNmIxMWFiNWRhODBhMzdhNTBiOGM4YzRmNTYwMzU5NjdkZGQ5ZmFlNTk0Nzc5NzU3ZWM2NGIwMHJlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==
```

**Comment by ChrisMcKee** [comment]
@CBaptiste the HMAC itself is fine 
image
After that its only converting to base64 

```
e0eecfea26b11ab5da80a37a50b8c8c4f56035967ddd9fae594779757ec64b00restrictIndices=algolia-csharp
```

becomes

```
ZTBlZWNmZWEyNmIxMWFiNWRhODBhMzdhNTBiOGM4YzRmNTYwMzU5NjdkZGQ5ZmFlNTk0Nzc5NzU3ZWM2NGIwMHJlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==
```
in online "to base 64"

in .net its 

```
ZTBlZWNmZWEyNmIxMWFiNWRhODBhMzdhNTBiOGM4YzRmNTYwMzU5NjdkZGQ5ZmFlNTk0Nzc5NzU3ZWM2NGIwMHJlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==
```

Colour me confused 😕

**Comment by ChrisMcKee** [comment]
@CBaptiste hey can you test this using your python client....

```
import hashlib
import hmac
import base64
from pprint import pprint
from algoliasearch import algoliasearch


client = algoliasearch.Client("TJ8JVLYYX7", 'myKey')

public_key = client.generate_secured_api_key('myKey', {'restrictIndices':'algolia-csharp'})

print(public_key)

clientb = algoliasearch.Client("TJ8JVLYYX7", public_key)

index = clientb.init_index("algolia-csharp")
index.add_objects([{"firstname":"Jimmie","lastname":"Barninger"}])

```

`algoliasearch.helpers.AlgoliaException: Invalid Application-ID or API key`

I get the same error regardless of client; wondering if theres an issue beyond the library here

**Comment by ChrisMcKee** [comment]
"search only api key" helps if I read before I type 💃

**Comment by ChrisMcKee** [comment]
Seems fine 👍 
```
Python (working secure api key)
NTk2ZWZiN2NkYTk3OWFkOGViOGZmNWU5ZjZiOTAyMWUyODc5OWJjMzI3MTIzMjc3OWE2OTU0ZGI5YjcyNWVlM3Jlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==
C#
NTk2ZWZiN2NkYTk3OWFkOGViOGZmNWU5ZjZiOTAyMWUyODc5OWJjMzI3MTIzMjc3OWE2OTU0ZGI5YjcyNWVlM3Jlc3RyaWN0SW5kaWNlcz1hbGdvbGlhLWNzaGFycA==
```

**Comment by CBaptiste** [comment]
The issue with the keys are fixed in that PR (c# client, I have the hash that passes th test with the original valid keys) but now I get some weird time out with 1 specific test, and then we are good...

**Comment by ChrisMcKee** [comment]
@CBaptiste cool... give it a couple of  months and netstandard 2  😉

**Comment by CBaptiste** [comment]
XUnit was running tests in parallel and was messing everything up.
Nugget about to be released \o/
We will be dropping 4 and 4.5 support

**Comment by ChrisMcKee** [comment]
Woot! Awesome

**Comment by ChrisMcKee** [comment]
@CBaptiste this going today/morrow?

**Comment by CBaptiste** [comment]
yes that s the plan !

**Comment by ChrisMcKee** [comment]
WOOOOOOOOT https://www.nuget.org/packages/Algolia.Search/4.0.0

**Comment by CBaptiste** [comment]
I cannot thank you enough @ChrisMcKee ! \o/

**Comment by ChrisMcKee** [comment]
@CBaptiste no probs; see you in a few weeks for round two 💃

**Pull request merged**
