### PR TITLE
Support to RemoveStopWords and AllRadius

### PR DESCRIPTION
**Pull request by CBaptiste**
Signed-off-by: CBaptiste <coquellebaptiste@gmail.com>

### CODE REVIEW

**Comment by speedblue** [comment]
Is this change backward compatible? I guess someone passing an integer will have to upgrade his code, isn't it?

**Comment by redox** [comment]
We need to keep the backward compatibility on all former prototypes; could you add the missing proxy functions @CBaptiste ?

**Comment by redox** [comment]
> Is this change backward compatible? I guess someone passing an integer will have to upgrade his code, isn't it?

Ahah, 2 sec delay!

**Comment by CBaptiste** [comment]
Damn ! I had not thought of that :( I will change that

**Comment by CBaptiste** [comment]
should be ok now

**Comment by redox** [comment]
LGTM 👍

**Pull request merged**
