### PR TITLE
Fixed: AA Testing flaky test

### PR DESCRIPTION
**Pull request by Ant-hem**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Need Doc update   | no

## Describe your change
Adding delete AA testing

### CODE REVIEW

**Comment by Ant-hem** [comment]
I still have the error time to time on line 105 on the CI with `await BaseTest.AnalyticsClient.GetABTestAsync(abTest.AbTestId.Value);` but I am not able to reproduce it locally

**Comment by Ant-hem** [comment]
@nunomaduro Did you spot any difference with your test suite?

**Comment by nunomaduro** [comment]
@Ant-hem No. All works as expected.

**Pull request merged**
