### PR TITLE
feat(serializer): JsonSerializer re-usable instance

### PR DESCRIPTION
**Pull request by Ant-hem**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| BC breaks?        | no     
| Need Doc update   | no

## Describe your change

In `src/Algolia.Search/Serializer/DefaultSerializer.cs`, let's have a re-usable instance of `JsonSerializer`  instead of a creating one for each call.  This will allow NewtonSoft to re-use  `JsonContract` instead of recreating one for each call.

## What problem is this fixing?

Performance issue under high load. See perf impact before and after the fix:

Before:

DOTTRACE_BEFORE

After:

DOTTRACE_AFTER

### CODE REVIEW

**Review by TomKlotzPro — APPROVED** [review]
LGTM @Ant-hem nice work! 🚀

**Comment by Ant-hem** [comment]
Sorry @TomKlotzPro forgot a `readonly` qualifier on the member.

**Comment by TomKlotzPro** [comment]
No problem @Ant-hem good catch!

**Comment by aymanh08** [comment]
Hello. Is this fix in the latest stable version of the SDK?

**Comment by Ant-hem** [comment]
Hello @aymanh08, it's not the latest release. 
Have you been experiencing performances issues with the SDK?

**Comment by aymanh08** [comment]
Sorry @Ant-hem for the late reply.
Yes I experienced performance issues with the SDK under heavy load, but this fix solves the problem for me. When do you think it'll be released? 
Thanks!

**Comment by Ant-hem** [comment]
Hi @aymanh08.  
Thanks for your answer and for confirming the fix solved the perf issue.
We'll release the fix in a minor version by the end of this week.
cc @TomKlotzPro

**Comment by TomKlotzPro** [comment]
Hello @aymanh08 ! 

The fix has been release in 6.9.1 -> https://www.nuget.org/packages/Algolia.Search/

Have a great day. 🚀

**Comment by hazemsusername** [comment]
Thanks, Tom and Antoine!

**Pull request merged**
